# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:

  test:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: unitt
          command: |
            echo ${AWS_CREDENTIALS}  | base64 --decode  > AWSCoreTests/Resources/credentials.json
       #     cat AWSCoreTests/Resources/credentials.json 
      - run :
          name: unitest
          command: xcodebuild -project AWSiOSSDKv2.xcodeproj -scheme AWSCloudWatch -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8'  -only-testing:AWSCloudWatchUnitTests  test  | xcpretty  
      - store_artifacts:
          path: output

  release_carthage:
    # Specify the Xcode version to use
    macos:
      xcode: "9.2.0"
    steps: 
      - checkout
      - run:
          name: upgrade carthage
          command: brew outdated carthage || brew upgrade carthage
      - run:
          name: Build Cathage
          command: carthage build --no-skip-current

      - run:
          name: Create Cathage Archive
          command: bash CreateCarthageArchive.sh   


  release_cocoapods:
    # Specify the Xcode version to use
    macos:
      xcode: "10.0.0"
    steps:
      - checkout  
      - run:
          name: Release cocoapods
          command : python3    cocoapods_release.py
  release_appledoc:
    # Specify the Xcode version to use
    macos:
      xcode: "9.2.0"
    steps:
      - checkout  
 
      - run:
          name: Install appledoc 
          command: |
            pwd
            pushd $TMPDIR
            git clone https://github.com/tomaz/appledoc
            cd appledoc
            bash install-appledoc.sh -t default
            popd 
            pwd

      - run:
          name: generate documents
          command: bash ./Scripts/GenerateAppleDocs.sh

      - run:
          name: copy documents
          command: |
            git checkout  gh-pages
            cp -R docs/html/*   docs/reference/

      - run:
          name: checkin documents
          command: |
            git add docs/reference
            git commit -m "Update document via CircleCI"
            git push -q https://${GITHUB_TOKEN}@github.com/aws/aws-sdk-ios.git  

workflows:
  version: 2
  build_and_test:
    jobs: 
      - test:
          filters:
            branches:
              only: testcircleci
      - release_carthage:
          filters:
            branches:
              only: master
      - release_cocoapods:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^test[0-9]+.[0-9]+.[0-9]+$/
      - release_appledoc:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^test[0-9]+.[0-9]+.[0-9]+$/
